version: '3'

services:
  app:
    image: 'spring-boot-postgresql'
    build:
      context: .
    container_name: spring-boot-postgresql
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/products
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - spring-boot-postgresql-network

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring-boot-postgresql-network

  sonarqube:
    image: 'sonarqube'
    ports:
      - 9000:9000
    networks:
      - spring-boot-postgresql-network

networks:
  spring-boot-postgresql-network:
    driver: bridge